@param gg.jte.Content controls
@param gg.jte.Content content

<div class="examples-shell feature-playground" id="feature-playground">
    <div class="feature-playground-controls">
        ${controls}
    </div>
    <div class="feature-playground-content-area">
        <div id="feature-playground-content-wrapper" class="playground-content-fixed-height">
            <div class="playground-content">
                ${content}
            </div>
        </div>
    </div>
</div>