@param io.availe.kreplicadocs.Example featureExample
@param gg.jte.Content tabs
@param gg.jte.Content initialContent

<div class="examples-shell" id="feature-playground">
    <div class="playground-tabs-wrapper">
        ${tabs}
    </div>
    <div id="feature-playground-content-wrapper" class="playground-content-fixed-height">
        <div class="playground-content">
            ${initialContent}
        </div>
    </div>
</div>